version: "3.6"

services:
  sbms-discovery-1:
    environment:
    - EUREKA_INSTANCE_LIST=${EUREKA_INSTANCE_LIST}
    image: jvandusen/sbms-discovery:${IMAGE_TAG}
    networks:
    - sbms-net
    ports:
    - "${DISCOVERY_PRIMARY_PORT}:8761"
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10m

  sbms-discovery-2:
    environment:
    - EUREKA_INSTANCE_LIST=${EUREKA_INSTANCE_LIST}
    image: jvandusen/sbms-discovery:${IMAGE_TAG}
    networks:
    - sbms-net
    ports:
    - "${DISCOVERY_SECONDARY_PORT}:8761"
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10m

  sbms-admin:
    environment:
    - EUREKA_INSTANCE_LIST=${EUREKA_INSTANCE_LIST}
    image: jvandusen/sbms-admin:${IMAGE_TAG}
    networks:
    - sbms-net
    ports:
    - "${ADMIN_PORT}:8080"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10m

  sbms-web:
    environment:
    - EUREKA_INSTANCE_LIST=${EUREKA_INSTANCE_LIST}
    image: jvandusen/sbms-web:${IMAGE_TAG}
    networks:
    - sbms-net
    ports:
    - "${WEB_PORT}:8080"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10m

  sbms-greeting:
    environment:
    - EUREKA_INSTANCE_LIST=${EUREKA_INSTANCE_LIST}
    - SPRING_DATA_MONGODB_HOST=sbms-mongo
    image: jvandusen/sbms-greeting:${IMAGE_TAG}
    networks:
    - sbms-net
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10m

  sbms-mongo:
    image: mongo
    networks:
    - sbms-net
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
    
networks:
  sbms-net:
    driver: overlay
    driver_opts:
      encrypted: "true"
