version: "3.6"

services:
  sbms-mongo:
    image: mongo
    networks:
    - sbms-net
    ports:
    - "${MONGODB_PORT}:27017"
    volumes:
    - "${MONGODB_DATA_PATH}:/data/db"
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      start_period: 1m

  sbms-discovery-1:
    environment:
      SPRING_PROFILES_ACTIVE: swarm
      EUREKA_INSTANCE_LIST: http://sbms-discovery-1:8080/eureka/,http://sbms-discovery-2:8080/eureka/
    image: jvandusen/sbms-discovery:${IMAGE_TAG}
    networks:
    - sbms-net
    ports:
    - "${DISCOVERY_PORT}:8080"
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      start_period: 5m

  sbms-discovery-2:
    environment:
      SPRING_PROFILES_ACTIVE: swarm
      EUREKA_INSTANCE_LIST: http://sbms-discovery-1:8080/eureka/,http://sbms-discovery-2:8080/eureka/
    image: jvandusen/sbms-discovery:${IMAGE_TAG}
    networks:
    - sbms-net
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      start_period: 5m

  sbms-admin:
    environment:
      SPRING_PROFILES_ACTIVE: swarm
      EUREKA_INSTANCE_LIST: http://sbms-discovery-1:8080/eureka/,http://sbms-discovery-2:8080/eureka/
    image: jvandusen/sbms-admin:${IMAGE_TAG}
    networks:
    - sbms-net
    ports:
    - "${ADMIN_PORT}:8080"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5m
        failure_action: continue
        monitor: 5m
        max_failure_ratio: 0.3
    healthcheck:
      start_period: 5m

  sbms-web:
    environment:
      SPRING_PROFILES_ACTIVE: swarm
      EUREKA_INSTANCE_LIST: http://sbms-discovery-1:8080/eureka/,http://sbms-discovery-2:8080/eureka/
    image: jvandusen/sbms-web:${IMAGE_TAG}
    networks:
    - sbms-net
    ports:
    - "${WEB_PORT}:8080"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5m
        failure_action: continue
        monitor: 5m
        max_failure_ratio: 0.3
    healthcheck:
      start_period: 5m

  sbms-greeting:
    environment:
      SPRING_PROFILES_ACTIVE: swarm
      EUREKA_INSTANCE_LIST: http://sbms-discovery-1:8080/eureka/,http://sbms-discovery-2:8080/eureka/
      SPRING_DATA_MONGODB_HOST: sbms-mongo
    image: jvandusen/sbms-greeting:${IMAGE_TAG}
    networks:
    - sbms-net
    ports:
    - "${GREETING_PORT}:8080"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5m
        failure_action: continue
        monitor: 5m
        max_failure_ratio: 0.3
    healthcheck:
      start_period: 5m

networks:
  sbms-net:
    name: ${NETWORK_NAME}
    driver: overlay
    driver_opts:
      encrypted: "true"
