version: "3.6"

services:
  sbms-admin:
    environment:
      EUREKA_INSTANCE_LIST: http://sbms-discovery:8761/eureka/
    image: jvandusen/sbms-admin:${IMAGE_TAG}
    networks:
    - sbms-net
    ports:
    - "${ADMIN_PORT}:8080"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5m
        failure_action: continue
        monitor: 5m
        max_failure_ratio: 0.3
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5m

  sbms-web:
    environment:
      EUREKA_INSTANCE_LIST: http://sbms-discovery:8761/eureka/
    image: jvandusen/sbms-web:${IMAGE_TAG}
    networks:
    - sbms-net
    ports:
    - "${WEB_PORT}:8080"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5m
        failure_action: continue
        monitor: 5m
        max_failure_ratio: 0.3
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5m

  sbms-greeting:
    environment:
      EUREKA_INSTANCE_LIST: http://sbms-discovery:8761/eureka/
      SPRING_DATA_MONGODB_HOST: sbms-mongo
    image: jvandusen/sbms-greeting:${IMAGE_TAG}
    networks:
    - sbms-net
    ports:
    - "${GREETING_PORT}:8080"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5m
        failure_action: continue
        monitor: 5m
        max_failure_ratio: 0.3
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5m

networks:
  sbms-net:
    name: ${NETWORK_NAME}
    external: true
