version: "3.6"

services:
  sbms-admin:
    environment:
      EUREKA_INSTANCE_LIST: ${EUREKA_INSTANCE_LIST}
    image: jvandusen/sbms-admin:${IMAGE_TAG}
    networks:
    - sbms-net
    ports:
    - "${ADMIN_PORT}:8080"
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5m
        failure_action: continue
        monitor: 5m
        max_failure_ratio: 0.3
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5m

  sbms-web:
    environment:
      EUREKA_INSTANCE_LIST: ${EUREKA_INSTANCE_LIST}
    image: jvandusen/sbms-web:${IMAGE_TAG}
    networks:
    - sbms-net
    ports:
    - "${WEB_PORT}:8080"
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5m
        failure_action: continue
        monitor: 5m
        max_failure_ratio: 0.3
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5m

  sbms-greeting:
    environment:
      EUREKA_INSTANCE_LIST: ${EUREKA_INSTANCE_LIST}
      SPRING_DATA_MONGODB_HOST: ${MONGODB_HOST}
      SPRING_DATA_MONGODB_PORT: ${MONGODB_PORT}
    image: jvandusen/sbms-greeting:${IMAGE_TAG}
    networks:
    - sbms-net
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5m
        failure_action: continue
        monitor: 5m
        max_failure_ratio: 0.3
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5m

networks:
  sbms-net:
    driver: overlay
    driver_opts:
      encrypted: "true"
