version: "3.6"

services:
  sbms-mongo:
    image: mongo
    ports:
    - "${MONGODB_PORT}:27017"
    volumes:
    - "${MONGODB_DATA_PATH}:/data/db"

  sbms-discovery:
    environment:
      EUREKA_INSTANCE_LIST: ${EUREKA_INSTANCE_LIST}
    image: jvandusen/sbms-discovery:${IMAGE_TAG}
    ports:
    - "${DISCOVERY_PORT}:8761"
