version: "3.6"

services:
  sbms-mongo-dev:
    image: mongo
    ports:
    - "${MONGO_PORT}:27017"
    volumes:
    - "${MONGO_DATA_PATH}:/data/db"

  sbms-discovery-1:
    environment:
      EUREKA_INSTANCE_LIST: ${EUREKA_INSTANCE_LIST}
    image: jvandusen/sbms-discovery:${IMAGE_TAG}
    ports:
    - "${DISCOVERY_PRIMARY_PORT}:8761"
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5m

  sbms-discovery-2:
    environment:
      EUREKA_INSTANCE_LIST: ${EUREKA_INSTANCE_LIST}
    image: jvandusen/sbms-discovery:${IMAGE_TAG}
    ports:
    - "${DISCOVERY_SECONDARY_PORT}:8761"
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5m
