version: "3.6"

services:
  sbms-mongo:
    image: mongo
    networks:
    - sbms-net
    ports:
    - "${MONGODB_PORT}:27017"
    volumes:
    - "${MONGODB_DATA_PATH}:/data/db"

  sbms-discovery:
    environment:
      EUREKA_INSTANCE_LIST: http://sbms-discovery:8761/eureka/
    image: jvandusen/sbms-discovery:${IMAGE_TAG}
    networks:
    - sbms-net
    ports:
    - "${DISCOVERY_PORT}:8761"

networks:
  sbms-net:
    name: ${NETWORK_NAME}
    external: true
