@Library('sbms-pipeline-shared@master') _

pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    environment {
        TEST_HOST = "172.24.140.88"
        DOCKER_HOST = "tcp://$TEST_HOST:2376"
        DOCKER_TLS_VERIFY = "1"
        DOCKER_CERT_PATH = "/root/.tls"
    }

    stages {
        stage('Tear Down Dev') {
            environment {
                APP_SWARM_MANAGER = "$TEST_HOST:2376"
                APP_STACK_NAME = "sbms-test-app"
            }
            steps {
                tearDown("$APP_SWARM_MANAGER", "$APP_STACK_NAME")
            }
        }
    }
    post {
        success {
            notify('INFO', 'The *TEST* environment has been taken down.')
        }
        failure {
            notify('WARN', 'The *TEST* environment did not shut down properly and may be in an unstable state.')
        }
    }
}
