pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    environment {
        DEV_HOST = "172.24.140.88"
    }

    stages {
        stage('Tear Down Dev') {
            environment {
                APP_SWARM_MANAGER = "$DEV_HOST:2375"
                APP_STACK_NAME = "sbms-test-app"
            }
            steps {
                sh "docker -H $APP_SWARM_MANAGER stack rm $APP_STACK_NAME"
            }
        }
    }
    post {
        success {
            slackSend ":warning: The TEST environment has been taken down."
        }
        failure {
            slackSend ":exclamation: The TEST environment did not shut down properly and may be in an unstable state."
        }
    }
}
