pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    triggers {
        pollSCM('H/5 8-16 * * 1-5')
        upstream(upstreamProjects: 'sbms-discovery,sbms-admin,sbms-web,sbms-greeting', threshold: hudson.model.Result.SUCCESS)
    }

    environment {
        DEV_HOST = "172.24.140.88"
    }

    stages {
        stage('Deploy to Dev') {
            environment {
                APP_SWARM_MANAGER = "$DEV_HOST:2375"
                APP_STACK_NAME = "sbms-dev-app"
                SOURCE_IMAGE_TAG = "latest"
                IMAGE_TAG = "dev"

                ADMIN_PORT = "19999"
                WEB_PORT = "18080"
                GREETING_PORT = "18100"
                DISCOVERY_PORT = "18761"

                MONGODB_DATA_PATH = "/opt/sbms/dev/mongodb"
                MONGODB_PORT = "27000"

                NETWORK_NAME = "sbms-dev-net"
            }
            steps {
                withDockerRegistry([url: '', credentialsId: 'DOCKER_HUB_CREDENTIALS']) {
                    sh "docker pull jvandusen/sbms-discovery:$SOURCE_IMAGE_TAG"
                    sh "docker pull jvandusen/sbms-admin:$SOURCE_IMAGE_TAG"
                    sh "docker pull jvandusen/sbms-web:$SOURCE_IMAGE_TAG"
                    sh "docker pull jvandusen/sbms-greeting:$SOURCE_IMAGE_TAG"

                    sh "docker tag jvandusen/sbms-discovery:$SOURCE_IMAGE_TAG jvandusen/sbms-discovery:$IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-admin:$SOURCE_IMAGE_TAG jvandusen/sbms-admin:$IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-web:$SOURCE_IMAGE_TAG jvandusen/sbms-web:$IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-greeting:$SOURCE_IMAGE_TAG jvandusen/sbms-greeting:$IMAGE_TAG"

                    sh "docker -H $APP_SWARM_MANAGER stack deploy --compose-file docker-compose.yml --resolve-image always --prune $APP_STACK_NAME"

                    sh "docker push jvandusen/sbms-discovery:$IMAGE_TAG"
                    sh "docker push jvandusen/sbms-admin:$IMAGE_TAG"
                    sh "docker push jvandusen/sbms-web:$IMAGE_TAG"
                    sh "docker push jvandusen/sbms-greeting:$IMAGE_TAG"
                }
            }
        }
    }
}
