pipeline {
    agent any

    triggers {
        pollSCM('H/5 8-16 * * 1-5')
        upstream(upstreamProjects: 'sbms-discovery,sbms-admin,sbms-web,sbms-greeting', threshold: hudson.model.Result.SUCCESS)
    }

    environment {
        DEV_INFRA_PRIMARY_MANAGER = '172.24.140.88:2375'
        DEV_INFRA_SECONDARY_MANAGER = '172.24.140.82:2375'
        DEV_APP_SWARM_MANAGER = '172.24.140.88:2375'
        DEV_APP_STACK_NAME = 'sbms-dev-app'
        DEV_SOURCE_IMAGE_TAG = 'latest'
        DEV_TARGET_IMAGE_TAG = 'dev'

        TEST_INFRA_PRIMARY_MANAGER = '172.24.140.88:2375'
        TEST_INFRA_SECONDARY_MANAGER = '172.24.140.82:2375'
        TEST_APP_SWARM_MANAGER = '172.24.140.88:2375'
        TEST_APP_STACK_NAME = 'sbms-test-app'
        TEST_SOURCE_IMAGE_TAG = 'dev'
        TEST_TARGET_IMAGE_TAG = 'test'
        TEST_PASSED_IMAGE_TAG = 'test-passed'

        UAT_INFRA_PRIMARY_MANAGER = '172.24.140.88:2375'
        UAT_INFRA_SECONDARY_MANAGER = '172.24.140.82:2375'
        UAT_APP_SWARM_MANAGER = '172.24.140.88:2375'
        UAT_APP_STACK_NAME = 'sbms-uat-app'
        UAT_SOURCE_IMAGE_TAG = 'test-passed'
        UAT_TARGET_IMAGE_TAG = 'uat'
    }
    
    stages {
        stage('Prepare Dev Infrastructure') {
            environment {
                COMPOSE_PROJECT_NAME = "sbms-dev-infra"
                IMAGE_TAG = "$DEV_TARGET_IMAGE_TAG"
                MONGODB_DATA_PATH = "/opt/sbms/dev/mongodb"
                MONGODB_PORT = "27000"
                DISCOVERY_PORT = "18761"
                EUREKA_INSTANCE_LIST = "http://dev-master-1:18761/eureka/,http://dev-node-1:18761/eureka/"
            }
            steps {
                sh "docker-compose -H $DEV_INFRA_PRIMARY_MANAGER -f sbms-infrastructure.yml pull"
                sh "docker-compose -H $DEV_INFRA_PRIMARY_MANAGER -f sbms-infrastructure.yml up -d"
                sh "docker-compose -H $DEV_INFRA_SECONDARY_MANAGER -f sbms-infrastructure.yml pull"
                sh "docker-compose -H $DEV_INFRA_SECONDARY_MANAGER -f sbms-infrastructure.yml up -d"
            }
        }
        stage('Deploy to Dev') {
            environment {
                IMAGE_TAG = "$DEV_TARGET_IMAGE_TAG"
                ADMIN_PORT = "19999"
                WEB_PORT = "18080"
                EUREKA_INSTANCE_LIST = "http://dev-master-1:18761/eureka/,http://dev-node-1:18761/eureka/"
                MONGODB_HOST = "dev-master-1"
                MONGODB_PORT = "27000"
            }
            steps {
                withDockerRegistry([url: '', credentialsId: 'DOCKER_HUB_CREDENTIALS']) {
                    sh "docker tag jvandusen/sbms-discovery:$DEV_SOURCE_IMAGE_TAG jvandusen/sbms-discovery:$DEV_TARGET_IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-admin:$DEV_SOURCE_IMAGE_TAG jvandusen/sbms-admin:$DEV_TARGET_IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-web:$DEV_SOURCE_IMAGE_TAG jvandusen/sbms-web:$DEV_TARGET_IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-greeting:$DEV_SOURCE_IMAGE_TAG jvandusen/sbms-greeting:$DEV_TARGET_IMAGE_TAG"
                    
                    sh "docker -H $DEV_APP_SWARM_MANAGER stack deploy --compose-file sbms-application.yml --resolve-image always --prune $DEV_APP_STACK_NAME"
                    
                    sh "docker push jvandusen/sbms-discovery:$DEV_TARGET_IMAGE_TAG"
                    sh "docker push jvandusen/sbms-admin:$DEV_TARGET_IMAGE_TAG"
                    sh "docker push jvandusen/sbms-web:$DEV_TARGET_IMAGE_TAG"
                    sh "docker push jvandusen/sbms-greeting:$DEV_TARGET_IMAGE_TAG"
                }
            }
        }
        stage('Prepare Images for Test') {
            steps {
                withDockerRegistry([url: '', credentialsId: 'DOCKER_HUB_CREDENTIALS']) {
                    sh "docker tag jvandusen/sbms-discovery:$TEST_SOURCE_IMAGE_TAG jvandusen/sbms-discovery:$TEST_TARGET_IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-admin:$TEST_SOURCE_IMAGE_TAG jvandusen/sbms-admin:$TEST_TARGET_IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-web:$TEST_SOURCE_IMAGE_TAG jvandusen/sbms-web:$TEST_TARGET_IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-greeting:$TEST_SOURCE_IMAGE_TAG jvandusen/sbms-greeting:$TEST_TARGET_IMAGE_TAG"

                    sh "docker push jvandusen/sbms-discovery:$TEST_TARGET_IMAGE_TAG"
                    sh "docker push jvandusen/sbms-admin:$TEST_TARGET_IMAGE_TAG"
                    sh "docker push jvandusen/sbms-web:$TEST_TARGET_IMAGE_TAG"
                    sh "docker push jvandusen/sbms-greeting:$TEST_TARGET_IMAGE_TAG"
                }
            }
        }
        stage('Prepare Test Infrastructure') {
            environment {
                COMPOSE_PROJECT_NAME = "sbms-test-infra"
                IMAGE_TAG = "$TEST_TARGET_IMAGE_TAG"
                MONGODB_DATA_PATH = "/opt/sbms/test/mongodb"
                MONGODB_PORT = "27001"
                DISCOVERY_PORT = "28761"
                EUREKA_INSTANCE_LIST = "http://dev-master-1:28761/eureka/,http://dev-node-1:28761/eureka/"
            }
            steps {
                sh "docker-compose -H $TEST_INFRA_PRIMARY_MANAGER -f sbms-infrastructure.yml pull"
                sh "docker-compose -H $TEST_INFRA_PRIMARY_MANAGER -f sbms-infrastructure.yml up -d"
                sh "docker-compose -H $TEST_INFRA_SECONDARY_MANAGER -f sbms-infrastructure.yml pull"
                sh "docker-compose -H $TEST_INFRA_SECONDARY_MANAGER -f sbms-infrastructure.yml up -d"
            }
        }
        stage('Deploy to Test') {
            environment {
                IMAGE_TAG = "$TEST_TARGET_IMAGE_TAG"
                ADMIN_PORT = "29999"
                WEB_PORT = "28080"
                EUREKA_INSTANCE_LIST = "http://dev-master-1:28761/eureka/,http://dev-node-1:28761/eureka/"
                MONGODB_HOST = "dev-master-1"
                MONGODB_PORT = "27001"
            }
            steps {
                withDockerRegistry([url: '', credentialsId: 'DOCKER_HUB_CREDENTIALS']) {
                    sh "docker -H $TEST_APP_SWARM_MANAGER stack deploy --compose-file sbms-application.yml --resolve-image always --prune $TEST_APP_STACK_NAME"
                }
            }
        }
        stage('Run Tests') {
            environment {
                COMPOSE_PROJECT_NAME = "sbms-test-infra"
                IMAGE_TAG = "$TEST_TARGET_IMAGE_TAG"
                MONGODB_DATA_PATH = "/opt/sbms/test/mongodb"
                MONGODB_PORT = "27001"
                DISCOVERY_PORT = "28761"
                EUREKA_INSTANCE_LIST = "http://dev-master-1:28761/eureka/,http://dev-node-1:28761/eureka/"
            }
            steps {
                // TODO: execute tests
                echo "insert tests here"
            }
            post {
                always {
                    sh "docker-compose -H $UAT_INFRA_PRIMARY_MANAGER -f sbms-infrastructure.yml down"
                    sh "docker-compose -H $UAT_INFRA_SECONDARY_MANAGER -f sbms-infrastructure.yml down"
                    sh "rm -rf $MONGODB_DATA_PATH/*"
                }
            }
        }
        stage ('Tag Tested Images') {
            steps {
                withDockerRegistry([url: '', credentialsId: 'DOCKER_HUB_CREDENTIALS']) {
                    sh "docker tag jvandusen/sbms-discovery:$TEST_TARGET_IMAGE_TAG jvandusen/sbms-discovery:$TEST_PASSED_IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-admin:$TEST_TARGET_IMAGE_TAG jvandusen/sbms-admin:$TEST_PASSED_IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-web:$TEST_TARGET_IMAGE_TAG jvandusen/sbms-web:$TEST_PASSED_IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-greeting:$TEST_TARGET_IMAGE_TAG jvandusen/sbms-greeting:$TEST_PASSED_IMAGE_TAG"

                    sh "docker push jvandusen/sbms-discovery:$TEST_PASSED_IMAGE_TAG"
                    sh "docker push jvandusen/sbms-admin:$TEST_PASSED_IMAGE_TAG"
                    sh "docker push jvandusen/sbms-web:$TEST_PASSED_IMAGE_TAG"
                    sh "docker push jvandusen/sbms-greeting:$TEST_PASSED_IMAGE_TAG"
                }
            }
        }
        stage('Prepare UAT Infrastructure') {
            environment {
                COMPOSE_PROJECT_NAME = "sbms-uat-infra"
                IMAGE_TAG = "$UAT_TARGET_IMAGE_TAG"
                MONGODB_DATA_PATH = "/opt/sbms/uat/mongodb"
                MONGODB_PORT = "27017"
                DISCOVERY_PORT = "8761"
                EUREKA_INSTANCE_LIST = "http://dev-master-1:8761/eureka/,http://dev-node-1:8761/eureka/"
            }
            steps {
                sh "docker-compose -H $UAT_INFRA_PRIMARY_MANAGER -f sbms-infrastructure.yml pull"
                sh "docker-compose -H $UAT_INFRA_PRIMARY_MANAGER -f sbms-infrastructure.yml up -d"
                sh "docker-compose -H $UAT_INFRA_SECONDARY_MANAGER -f sbms-infrastructure.yml pull"
                sh "docker-compose -H $UAT_INFRA_SECONDARY_MANAGER -f sbms-infrastructure.yml up -d"
            }
        }
        stage('Deploy to UAT') {
            environment {
                IMAGE_TAG = "$UAT_TARGET_IMAGE_TAG"
                ADMIN_PORT = "9999"
                WEB_PORT = "8080"
                EUREKA_INSTANCE_LIST = "http://dev-master-1:8761/eureka/,http://dev-node-1:8761/eureka/"
                MONGODB_HOST = "dev-master-1"
                MONGODB_PORT = "27017"
            }
            steps {
                withDockerRegistry([url: '', credentialsId: 'DOCKER_HUB_CREDENTIALS']) {
                    sh "docker tag jvandusen/sbms-discovery:$UAT_SOURCE_IMAGE_TAG jvandusen/sbms-discovery:$UAT_TARGET_IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-admin:$UAT_SOURCE_IMAGE_TAG jvandusen/sbms-admin:$UAT_TARGET_IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-web:$UAT_SOURCE_IMAGE_TAG jvandusen/sbms-web:$UAT_TARGET_IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-greeting:$UAT_SOURCE_IMAGE_TAG jvandusen/sbms-greeting:$UAT_TARGET_IMAGE_TAG"

                    sh "docker -H $UAT_APP_SWARM_MANAGER stack deploy --compose-file sbms-application.yml --resolve-image always --prune $UAT_APP_STACK_NAME"

                    sh "docker push jvandusen/sbms-discovery:$UAT_TARGET_IMAGE_TAG"
                    sh "docker push jvandusen/sbms-admin:$UAT_TARGET_IMAGE_TAG"
                    sh "docker push jvandusen/sbms-web:$UAT_TARGET_IMAGE_TAG"
                    sh "docker push jvandusen/sbms-greeting:$UAT_TARGET_IMAGE_TAG"
                }
            }
        }
    }
}
