@Library('sbms-pipeline-shared@master') _

pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    triggers {
        pollSCM('H/5 8-16 * * 1-5')
        upstream(upstreamProjects: 'sbms-pipeline-test', threshold: hudson.model.Result.SUCCESS)
    }

    environment {
        DEV_HOST = "172.24.140.88"
    }

    stages {
        stage('Deploy to UAT') {
            environment {
                APP_SWARM_MANAGER = "$DEV_HOST:2375"
                APP_STACK_NAME = "sbms-uat-app"
                SOURCE_IMAGE_TAG = "test-passed"
                IMAGE_TAG = "uat"

                ADMIN_PORT = "9999"
                WEB_PORT = "8080"
                GREETING_PORT = "8100"
                DISCOVERY_PORT = "8761"

                MONGODB_DATA_PATH = "/opt/sbms/uat/mongodb"
                MONGODB_PORT = "27017"

                NETWORK_NAME = "sbms-uat-net"
            }
            steps {
                withDockerRegistry([url: '', credentialsId: 'DOCKER_HUB_CREDENTIALS']) {
                    pull("$SOURCE_IMAGE_TAG")
                    tag("$SOURCE_IMAGE_TAG", "$IMAGE_TAG")
                    deploy("$APP_SWARM_MANAGER", "$APP_STACK_NAME")
                    push("$IMAGE_TAG")
                }
            }
        }
    }
    post {
        success {
            notify('INFO', 'The *UAT* environment has been deployed.')
        }
        failure {
            notify('WARN', 'The *UAT* environment did not deploy properly and may be in an unstable state.')
        }
    }
}
