pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    triggers {
        pollSCM('H/5 8-16 * * 1-5')
        upstream(upstreamProjects: 'sbms-test', threshold: hudson.model.Result.SUCCESS)
    }

    environment {
        DEV_HOST = "172.24.140.88"
    }

    stages {
        stage('Deploy to UAT') {
            environment {
                APP_SWARM_MANAGER = "$DEV_HOST:2375"
                APP_STACK_NAME = "sbms-uat-app"
                SOURCE_IMAGE_TAG = "test-passed"
                IMAGE_TAG = "uat"

                ADMIN_PORT = "9999"
                WEB_PORT = "8080"
                GREETING_PORT = "8100"
                DISCOVERY_PORT = "8761"

                MONGODB_DATA_PATH = "/opt/sbms/uat/mongodb"
                MONGODB_PORT = "27017"

                NETWORK_NAME = "sbms-uat-net"
            }
            steps {
                withDockerRegistry([url: '', credentialsId: 'DOCKER_HUB_CREDENTIALS']) {
                    sh "docker pull jvandusen/sbms-discovery:$SOURCE_IMAGE_TAG"
                    sh "docker pull jvandusen/sbms-admin:$SOURCE_IMAGE_TAG"
                    sh "docker pull jvandusen/sbms-web:$SOURCE_IMAGE_TAG"
                    sh "docker pull jvandusen/sbms-greeting:$SOURCE_IMAGE_TAG"

                    sh "docker tag jvandusen/sbms-discovery:$SOURCE_IMAGE_TAG jvandusen/sbms-discovery:$IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-admin:$SOURCE_IMAGE_TAG jvandusen/sbms-admin:$IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-web:$SOURCE_IMAGE_TAG jvandusen/sbms-web:$IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-greeting:$SOURCE_IMAGE_TAG jvandusen/sbms-greeting:$IMAGE_TAG"

                    sh "docker -H $APP_SWARM_MANAGER stack deploy --compose-file docker-compose.yml --resolve-image always --prune $APP_STACK_NAME"

                    sh "docker push jvandusen/sbms-discovery:$IMAGE_TAG"
                    sh "docker push jvandusen/sbms-admin:$IMAGE_TAG"
                    sh "docker push jvandusen/sbms-web:$IMAGE_TAG"
                    sh "docker push jvandusen/sbms-greeting:$IMAGE_TAG"
                }
            }
        }
    }
    post {
        success {
            slackSend ":sunrise: The UAT environment has been deployed."
        }
        failure {
            slackSend ":exclamation: The UAT environment did not deploy properly and may be in an unstable state."
        }
    }
}
