@Library('sbms-pipeline-shared@master') _

pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    environment {
        PROD_HOST = "172.24.140.83"
    }

    stages {
        stage('Tear Down Dev') {
            environment {
                APP_SWARM_MANAGER = "$PROD_HOST:2375"
                APP_STACK_NAME = "sbms-prod-app"
            }
            steps {
                tearDown("$APP_SWARM_MANAGER", "$APP_STACK_NAME")
            }
        }
    }
    post {
        success {
            notify('PROD_INFO', '*The PROD environment has been taken down.*')
        }
        failure {
            notify('PROD_WARN', '*The PROD environment did not shut down properly and may be in an unstable state.*')
        }
    }
}
