@Library('sbms-pipeline-shared@master') _

pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    environment {
        HOST = "prod"
        PORT = "2376"

        SOURCE_IMAGE_TAG = "rc"
        IMAGE_TAG = "prod"

        ADMIN_PORT = "9999"
        WEB_PORT = "8080"
        GREETING_PORT = "8100"
        DISCOVERY_PORT = "8761"

        MONGODB_DATA_PATH = "/opt/sbms/mongodb"
        MONGODB_PORT = "27017"

        NETWORK_NAME = "sbms-prod-net"
    }
    
    stages {
        stage('Prepare Data Directory') {
            steps {
                sh "mkdir -p $MONGODB_DATA_PATH"
            }
        }
        stage('Deploy Application') {
            steps {
                dockerDeploy("tcp://$HOST:$PORT", "sbms-prod-app")
            }
        }
    }
    post {
        success {
            notify('PROD_SUCCESS', '*Production deployment successfully completed!*')
        }
        failure {
            notify('PROD_FAIL', '*Production deployment failed!*')
        }
    }
}
