pipeline {
    agent any

    environment {
        SWARM_MANAGER = '172.24.140.83:2375'
        STACK_NAME = 'sbms-prod'
        SOURCE_IMAGE_TAG = 'rc'
        TARGET_IMAGE_TAG = 'prod'
        DISCOVERY_PRIMARY_PORT = "8761"
        DISCOVERY_SECONDARY_PORT = "8762"
        ADMIN_PORT = "9999"
        WEB_PORT = "8080"
        EUREKA_INSTANCE_LIST = "http://prod-master-1:8761/eureka/,http://prod-master-2:8762/eureka/"
    }
    
    stages {
        stage('Deploy') {
            environment {
                IMAGE_TAG = "$TARGET_IMAGE_TAG"
            }
            steps {
                withDockerRegistry([url: '', credentialsId: 'DOCKER_HUB_CREDENTIALS']) {
                    sh "docker tag jvandusen/sbms-discovery:$SOURCE_IMAGE_TAG jvandusen/sbms-discovery:$TARGET_IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-admin:$SOURCE_IMAGE_TAG jvandusen/sbms-admin:$TARGET_IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-web:$SOURCE_IMAGE_TAG jvandusen/sbms-web:$TARGET_IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-greeting:$SOURCE_IMAGE_TAG jvandusen/sbms-greeting:$TARGET_IMAGE_TAG"

                    sh "docker -H $SWARM_MANAGER stack deploy --compose-file docker-compose.yml --resolve-image always --prune $STACK_NAME"

                    sh "docker push jvandusen/sbms-discovery:$TARGET_IMAGE_TAG"
                    sh "docker push jvandusen/sbms-admin:$TARGET_IMAGE_TAG"
                    sh "docker push jvandusen/sbms-web:$TARGET_IMAGE_TAG"
                    sh "docker push jvandusen/sbms-greeting:$TARGET_IMAGE_TAG"
                }
            }
        }
    }
}
