pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    environment {
        PROD_HOST = "172.24.140.83"
    }
    
    stages {
        stage('Deploy Application') {
            environment {
                APP_SWARM_MANAGER = "$PROD_HOST:2375"
                APP_STACK_NAME = "sbms-prod-app"
                SOURCE_IMAGE_TAG = "rc"
                IMAGE_TAG = "prod"

                ADMIN_PORT = "9999"
                WEB_PORT = "8080"
                GREETING_PORT = "8100"
                DISCOVERY_PORT = "8761"

                MONGODB_DATA_PATH = "/opt/sbms/mongodb"
                MONGODB_PORT = "27017"

                NETWORK_NAME = "sbms-prod-net"
            }
            steps {
                withDockerRegistry([url: '', credentialsId: 'DOCKER_HUB_CREDENTIALS']) {
                    sh "docker pull jvandusen/sbms-discovery:$SOURCE_IMAGE_TAG"
                    sh "docker pull jvandusen/sbms-admin:$SOURCE_IMAGE_TAG"
                    sh "docker pull jvandusen/sbms-web:$SOURCE_IMAGE_TAG"
                    sh "docker pull jvandusen/sbms-greeting:$SOURCE_IMAGE_TAG"

                    sh "docker tag jvandusen/sbms-discovery:$SOURCE_IMAGE_TAG jvandusen/sbms-discovery:$IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-admin:$SOURCE_IMAGE_TAG jvandusen/sbms-admin:$IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-web:$SOURCE_IMAGE_TAG jvandusen/sbms-web:$IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-greeting:$SOURCE_IMAGE_TAG jvandusen/sbms-greeting:$IMAGE_TAG"

                    sh "docker -H $APP_SWARM_MANAGER stack deploy --compose-file docker-compose.yml --resolve-image always --prune $APP_STACK_NAME"

                    sh "docker push jvandusen/sbms-discovery:$IMAGE_TAG"
                    sh "docker push jvandusen/sbms-admin:$IMAGE_TAG"
                    sh "docker push jvandusen/sbms-web:$IMAGE_TAG"
                    sh "docker push jvandusen/sbms-greeting:$IMAGE_TAG"
                }
            }
        }
    }
    post {
        success {
            slackSend "<${env.BUILD_URL}|${env.JOB_NAME} #${env.BUILD_NUMBER}>: :trophy: *Production deployment successfully completed!*"
        }
        failure {
            slackSend "<${env.BUILD_URL}|${env.JOB_NAME} #${env.BUILD_NUMBER}>: :boom: *Production deployment failed!*"
        }
    }
}
