@Library('sbms-pipeline-shared@master') _

pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    environment {
        HOST = "dev"
        PORT = "2376"
    }
    
    stages {
        stage('Tear Down Dev') {
            steps {
                dockerTearDown("tcp://$HOST:$PORT", "sbms-dev")
            }
        }
    }
    post {
        success {
            notify('INFO', 'The *DEV* environment has been taken down.')
        }
        failure {
            notify('WARN', 'The *DEV* environment did not shut down properly and may be in an unstable state.')
        }
    }
}
