pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    environment {
        DEV_HOST = "172.24.140.88"
    }
    
    stages {
        environment {
            APP_SWARM_MANAGER = "$DEV_HOST:2375"
            APP_STACK_NAME = "sbms-dev-app"
        }
        stage('Tear Down Dev') {
            steps {
                sh "docker -H $APP_SWARM_MANAGER stack rm $APP_STACK_NAME"
            }
        }
    }
}
