pipeline {
    agent any

    environment {
        SWARM_MANAGER = '172.24.140.94:2375'
        STACK_NAME = 'sbms-dev'
    }
    
    stages {
        stage('Tear Down Dev') {
            steps {
                sh "docker -H $SWARM_MANAGER stack rm $STACK_NAME"
            }
        }
    }
}
