pipeline {
    agent any

    environment {
        SOURCE_IMAGE_TAG = 'uat'
        IMAGE_TAG = 'rc'
    }
    
    stages {
        stage('Prepare Release Candidate') {
            steps {
                withDockerRegistry([url: '', credentialsId: 'DOCKER_HUB_CREDENTIALS']) {
                    sh "docker tag jvandusen/sbms-discovery:$SOURCE_IMAGE_TAG jvandusen/sbms-discovery:$IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-admin:$SOURCE_IMAGE_TAG jvandusen/sbms-admin:$IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-web:$SOURCE_IMAGE_TAG jvandusen/sbms-web:$IMAGE_TAG"
                    sh "docker tag jvandusen/sbms-greeting:$SOURCE_IMAGE_TAG jvandusen/sbms-greeting:$IMAGE_TAG"

                    sh "docker push jvandusen/sbms-discovery:$IMAGE_TAG"
                    sh "docker push jvandusen/sbms-admin:$IMAGE_TAG"
                    sh "docker push jvandusen/sbms-web:$IMAGE_TAG"
                    sh "docker push jvandusen/sbms-greeting:$IMAGE_TAG"
                }
            }
        }
    }
}
