pipeline {
    agent any

    environment {
        SWARM_MANAGER = '172.24.140.89:2375'
        STACK_NAME = 'sbms-uat'
    }
    
    stages {
        stage('Tear Down UAT') {
            steps {
                sh "docker -H $SWARM_MANAGER stack rm $STACK_NAME"
            }
        }
    }
}
