@Library('sbms-pipeline-shared@master') _

pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    environment {
        HOST = "uat"
        PORT = "2376"

        SOURCE_IMAGE_TAG = "test-passed"
        IMAGE_TAG = "uat"

        ADMIN_PORT = "9999"
        WEB_PORT = "80"
        GREETING_PORT = "8100"
        DISCOVERY_PORT = "8761"

        MONGODB_DATA_PATH = "/opt/sbms/uat/mongodb"
        MONGODB_PORT = "27017"

        NETWORK_NAME = "sbms-uat-net"
    }

    stages {
        stage('Prepare Data Directory') {
            steps {
                sh "mkdir -p $MONGODB_DATA_PATH"
            }
        }
        stage('Deploy to UAT') {
            steps {
                dockerDeploy("tcp://$HOST:$PORT", "sbms-uat")
            }
        }
    }
    post {
        success {
            notify('INFO', 'The *UAT* environment has been deployed.')
        }
        failure {
            notify('WARN', 'The *UAT* environment did not deploy properly and may be in an unstable state.')
        }
    }
}
