@Library('sbms-pipeline-shared@master') _

pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        timeout(time: 15, unit: 'MINUTES')
    }

    environment {
        UAT_HOST = "uat"
        DOCKER_HOST = "tcp://$UAT_HOST:2376"
        DOCKER_TLS_VERIFY = "1"
        DOCKER_CERT_PATH = "/root/.tls"
    }

    stages {
        stage('Deploy to UAT') {
            environment {
                STACK_NAME = "sbms-uat-app"
                SOURCE_IMAGE_TAG = "test-passed"
                IMAGE_TAG = "uat"

                ADMIN_PORT = "39999"
                WEB_PORT = "38080"
                GREETING_PORT = "38100"
                DISCOVERY_PORT = "38761"

                MONGODB_DATA_PATH = "/opt/sbms/uat/mongodb"
                MONGODB_PORT = "27002"

                NETWORK_NAME = "sbms-uat-net"
            }
            steps {
                withDockerRegistry([url: '', credentialsId: 'DOCKER_HUB_CREDENTIALS']) {
                    dockerPull("$SOURCE_IMAGE_TAG")
                    dockerTag("$SOURCE_IMAGE_TAG", "$IMAGE_TAG")
                    dockerDeploy("$STACK_NAME")
                    dockerPush("$IMAGE_TAG")
                }
            }
        }
    }
    post {
        success {
            notify('INFO', 'The *UAT* environment has been deployed.')
        }
        failure {
            notify('WARN', 'The *UAT* environment did not deploy properly and may be in an unstable state.')
        }
    }
}
